//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Geo.Tools.CrsTransformer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrsTransformer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrsTransformer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Geo.Tools.CrsTransformer.CrsTransformer", typeof(CrsTransformer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRS EPSG coordinate reference system transformer tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom EPSG.
        /// </summary>
        internal static string CustomEpsg {
            get {
                return ResourceManager.GetString("CustomEpsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPSG code.
        /// </summary>
        internal static string CustomEpsgPlaceholder {
            get {
                return ResourceManager.GetString("CustomEpsgPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform geometries between coordinate reference systems (EPSG codes).
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 spaces.
        /// </summary>
        internal static string FourSpaces {
            get {
                return ResourceManager.GetString("FourSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoJSON.
        /// </summary>
        internal static string GeoJson {
            get {
                return ResourceManager.GetString("GeoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation.
        /// </summary>
        internal static string Indentation {
            get {
                return ResourceManager.GetString("Indentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the indentation for GeoJSON output.
        /// </summary>
        internal static string IndentationDescription {
            get {
                return ResourceManager.GetString("IndentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input format.
        /// </summary>
        internal static string InputFormat {
            get {
                return ResourceManager.GetString("InputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the input geometry format.
        /// </summary>
        internal static string InputFormatDescription {
            get {
                return ResourceManager.GetString("InputFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid EPSG code&gt;.
        /// </summary>
        internal static string InvalidEpsgCode {
            get {
                return ResourceManager.GetString("InvalidEpsgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid input geometry&gt;.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRS/EPSG Coordinate Transformer.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRS Transformer.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source CRS.
        /// </summary>
        internal static string SourceCrs {
            get {
                return ResourceManager.GetString("SourceCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source coordinate reference system (EPSG code).
        /// </summary>
        internal static string SourceCrsDescription {
            get {
                return ResourceManager.GetString("SourceCrsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        internal static string SwapCrs {
            get {
                return ResourceManager.GetString("SwapCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target CRS.
        /// </summary>
        internal static string TargetCrs {
            get {
                return ResourceManager.GetString("TargetCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target coordinate reference system (EPSG code).
        /// </summary>
        internal static string TargetCrsDescription {
            get {
                return ResourceManager.GetString("TargetCrsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search EPSG.
        /// </summary>
        internal static string SearchEpsg {
            get {
                return ResourceManager.GetString("SearchEpsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;Transformation error&gt;.
        /// </summary>
        internal static string TransformationError {
            get {
                return ResourceManager.GetString("TransformationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2 spaces.
        /// </summary>
        internal static string TwoSpaces {
            get {
                return ResourceManager.GetString("TwoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT.
        /// </summary>
        internal static string Wkt {
            get {
                return ResourceManager.GetString("Wkt", resourceCulture);
            }
        }
    }
}
