//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Geo.Tools.GeoJsonWkt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeoJsonWktConverter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeoJsonWktConverter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Geo.Tools.GeoJsonWkt.GeoJsonWktConverter", typeof(GeoJsonWktConverter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoJSON to KWT and WKT to GeoJSON converter tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which conversion mode you want to use.
        /// </summary>
        internal static string ConversionDescription {
            get {
                return ResourceManager.GetString("ConversionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to convert from GeoJSON or Yaml.
        /// </summary>
        internal static string ConversionOptionDescription {
            get {
                return ResourceManager.GetString("ConversionOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        internal static string ConversionTitle {
            get {
                return ResourceManager.GetString("ConversionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert GeoJSON data to WKT and vice versa.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 spaces.
        /// </summary>
        internal static string FourSpaces {
            get {
                return ResourceManager.GetString("FourSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoJSON to WKT.
        /// </summary>
        internal static string GeoJSONToWKT {
            get {
                return ResourceManager.GetString("GeoJSONToWKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation.
        /// </summary>
        internal static string Indentation {
            get {
                return ResourceManager.GetString("Indentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which indentation you want to use.
        /// </summary>
        internal static string IndentationOptionDescription {
            get {
                return ResourceManager.GetString("IndentationOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file selected does not exist.
        /// </summary>
        internal static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or path to a file to convert from GeoJSON or WKT.
        /// </summary>
        internal static string InputOptionDescription {
            get {
                return ResourceManager.GetString("InputOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid GeoJSON data&gt;.
        /// </summary>
        internal static string InvalidGeoJSON {
            get {
                return ResourceManager.GetString("InvalidGeoJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an input text or an input file.
        /// </summary>
        internal static string InvalidInputOrFileCommand {
            get {
                return ResourceManager.GetString("InvalidInputOrFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid WKT data&gt;.
        /// </summary>
        internal static string InvalidWKT {
            get {
                return ResourceManager.GetString("InvalidWKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoJSON &lt;&gt; WKT Converter.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the output file.
        /// </summary>
        internal static string OutputFileDescription {
            get {
                return ResourceManager.GetString("OutputFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoJSON &lt;&gt; YAML.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 spaces.
        /// </summary>
        internal static string TwoSpaces {
            get {
                return ResourceManager.GetString("TwoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT to GeoJSON.
        /// </summary>
        internal static string WKTToGeoJSON {
            get {
                return ResourceManager.GetString("WKTToGeoJSON", resourceCulture);
            }
        }
    }
}
